# Generated by Django 5.2.17 on 2026-09-15 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='tier',
            field=models.CharField(default='Inicial', max_length=40),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_rides',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
