from django.db import migrations


SCHEMA_SQL = """
ALTER TABLE perfil_pasajero
    ADD COLUMN IF NOT EXISTS cantidad_calificaciones INTEGER NOT NULL DEFAULT 0;

ALTER TABLE perfil_conductor
    ADD COLUMN IF NOT EXISTS cantidad_calificaciones INTEGER NOT NULL DEFAULT 0;

ALTER TABLE viaje
    ADD COLUMN IF NOT EXISTS origen_direccion VARCHAR(255),
    ADD COLUMN IF NOT EXISTS destino_direccion VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tipo_vehiculo VARCHAR(30) NOT NULL DEFAULT 'economy',
    ADD COLUMN IF NOT EXISTS oferta_inicial NUMERIC(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS calificacion_pasajero SMALLINT,
    ADD COLUMN IF NOT EXISTS calificacion_conductor SMALLINT,
    ADD COLUMN IF NOT EXISTS etiqueta_pasajero VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS etiqueta_conductor VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ubicacion_pasajero geometry(Point, 4326),
    ADD COLUMN IF NOT EXISTS ubicacion_conductor geometry(Point, 4326),
    ADD COLUMN IF NOT EXISTS api_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ofertas
    ADD COLUMN IF NOT EXISTS api_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS viaje_api_id_uniq ON viaje (api_id);
CREATE UNIQUE INDEX IF NOT EXISTS ofertas_api_id_uniq ON ofertas (api_id);
CREATE INDEX IF NOT EXISTS viaje_estado_fecha_idx ON viaje (estado_viaje, fecha_solicitud DESC);
CREATE INDEX IF NOT EXISTS ofertas_viaje_estado_idx ON ofertas (id_viaje, estado_oferta);
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(SCHEMA_SQL, reverse_sql=migrations.RunSQL.noop),
    ]