# Generated by Django 5.2.17 on 2026-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0001_extend_api_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusWithdrawal',
            fields=[
                ('id', models.UUIDField(db_column='id_retiro', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='monto_solicitado', decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, db_column='metodo_pago_destino', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='estado_retiro', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_solicitud', null=True)),
            ],
            options={
                'db_table': 'retiro_bonificacion',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(db_column='id_documento', primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, db_column='tipo_documento', max_length=50, null=True)),
                ('file_url', models.CharField(blank=True, db_column='url_archivo', max_length=500, null=True)),
                ('validation_status', models.CharField(blank=True, db_column='estado_validacion', max_length=20, null=True)),
                ('expires_at', models.DateField(blank=True, db_column='fecha_vencimiento', null=True)),
            ],
            options={
                'db_table': 'documentos',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(db_column='id_conductor', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='estado_cuenta', max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, db_column='doc_identidad', max_length=20, null=True)),
                ('total_rides', models.IntegerField(blank=True, db_column='viajes_completados', null=True)),
                ('rating', models.DecimalField(blank=True, db_column='calificacion_promedio', decimal_places=2, max_digits=3, null=True)),
                ('points', models.IntegerField(blank=True, db_column='puntos_co', null=True)),
                ('points_left', models.IntegerField(blank=True, db_column='puntos_co_i', null=True)),
                ('points_right', models.IntegerField(blank=True, db_column='puntos_co_d', null=True)),
                ('wallet_balance', models.DecimalField(blank=True, db_column='saldo_bolsa_disponible', decimal_places=2, max_digits=10, null=True)),
                ('reserved_balance', models.DecimalField(blank=True, db_column='saldo_bolsa_reservado', decimal_places=2, max_digits=10, null=True)),
                ('bonus_balance', models.DecimalField(blank=True, db_column='saldo_bonos_disponible', decimal_places=2, max_digits=10, null=True)),
                ('network_side', models.CharField(blank=True, db_column='lado_red', max_length=20, null=True)),
                ('rating_count', models.IntegerField(db_column='cantidad_calificaciones', default=0)),
            ],
            options={
                'db_table': 'perfil_conductor',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('id', models.UUIDField(db_column='id_transaccion', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('movement_type', models.CharField(blank=True, db_column='tipo_movimiento', max_length=30, null=True)),
                ('payment_reference', models.CharField(blank=True, db_column='referencia_wompi', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_transaccion', null=True)),
                ('status', models.CharField(blank=True, db_column='estado_transaccion', max_length=20, null=True)),
            ],
            options={
                'db_table': 'transacciones',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.UUIDField(db_column='id_pasajero', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, db_column='calificacion_promedio', decimal_places=2, max_digits=3, null=True)),
                ('default_payment', models.CharField(blank=True, db_column='califi_pago_defecto', max_length=30, null=True)),
                ('total_rides', models.IntegerField(blank=True, db_column='viajes_completados', null=True)),
                ('points', models.IntegerField(blank=True, db_column='puntos_pa', null=True)),
                ('points_left', models.IntegerField(blank=True, db_column='puntos_pa_i', null=True)),
                ('points_right', models.IntegerField(blank=True, db_column='puntos_pa_d', null=True)),
                ('bonus_balance', models.DecimalField(blank=True, db_column='saldo_bonos_disponible', decimal_places=2, max_digits=10, null=True)),
                ('network_side', models.CharField(blank=True, db_column='lado_red_p', max_length=20, null=True)),
                ('rating_count', models.IntegerField(db_column='cantidad_calificaciones', default=0)),
            ],
            options={
                'db_table': 'perfil_pasajero',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.UUIDField(db_column='id_historial', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='cantidad_puntos', null=True)),
                ('reason', models.CharField(blank=True, db_column='motivo', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_registro', null=True)),
                ('network_role', models.CharField(blank=True, db_column='rol_red', max_length=20, null=True)),
            ],
            options={
                'db_table': 'historial_puntos',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.UUIDField(db_column='id_rango', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre_rango', max_length=30, null=True)),
                ('bono_multiplicador', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('pi_minimos', models.IntegerField(blank=True, null=True)),
                ('pg_i_minimos', models.IntegerField(blank=True, null=True)),
                ('pg_d_minimos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rangos',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(db_column='id_viaje', primary_key=True, serialize=False)),
                ('final_fare', models.DecimalField(blank=True, db_column='precio_final', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='estado_viaje', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_solicitud', null=True)),
                ('distance_meters', models.IntegerField(blank=True, db_column='distancia_metros', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, db_column='tiempo_segundos', null=True)),
                ('estimated_price', models.DecimalField(blank=True, db_column='tarifa_recomendada', decimal_places=2, max_digits=10, null=True)),
                ('reserved_debit', models.DecimalField(blank=True, db_column='debito_bolsa_reservado', decimal_places=2, max_digits=10, null=True)),
                ('pickup_code', models.CharField(blank=True, db_column='pin_seguridad', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('origin', models.CharField(blank=True, db_column='origen_direccion', max_length=255, null=True)),
                ('destination', models.CharField(blank=True, db_column='destino_direccion', max_length=255, null=True)),
                ('vehicle_type', models.CharField(db_column='tipo_vehiculo', default='economy', max_length=30)),
                ('offer_amount', models.DecimalField(db_column='oferta_inicial', decimal_places=2, default=0, max_digits=10)),
                ('passenger_rating', models.PositiveSmallIntegerField(blank=True, db_column='calificacion_pasajero', null=True)),
                ('driver_rating', models.PositiveSmallIntegerField(blank=True, db_column='calificacion_conductor', null=True)),
                ('passenger_location_label', models.CharField(blank=True, db_column='etiqueta_pasajero', default='', max_length=255)),
                ('driver_location_label', models.CharField(blank=True, db_column='etiqueta_conductor', default='', max_length=255)),
            ],
            options={
                'db_table': 'viaje',
                'ordering': ['-created_at'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.UUIDField(db_column='id_oferta', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='precio_propuesto', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='estado_oferta', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_oferta', null=True)),
            ],
            options={
                'db_table': 'ofertas',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(db_column='id_ticket', primary_key=True, serialize=False)),
                ('issue_type', models.CharField(blank=True, db_column='tipo_incidencia', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_column='estado_ticket', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fecha_apertura', null=True)),
            ],
            options={
                'db_table': 'tickets_de_soporte',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.UUIDField(db_column='id_tarifa', primary_key=True, serialize=False)),
                ('precio_base_legal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vigencia_ano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarifa',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.UUIDField(db_column='id_bono', primary_key=True, serialize=False)),
                ('network_role', models.CharField(blank=True, db_column='rol_red', max_length=20, null=True)),
                ('reason', models.CharField(blank=True, db_column='motivo_bono', max_length=50, null=True)),
                ('generated_points', models.IntegerField(blank=True, db_column='up_generadas', null=True)),
                ('liquidated_amount', models.DecimalField(blank=True, db_column='monto_liquidado', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='estado_bono', max_length=20, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_column='fecha_cierre', null=True)),
            ],
            options={
                'db_table': 'bonificacion_usuario',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(db_column='id_vehiculo', primary_key=True, serialize=False)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_model', models.CharField(blank=True, db_column='marca_modelo', max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, db_column='estado_vehiculo', max_length=20, null=True)),
            ],
            options={
                'db_table': 'vehiculo',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id', models.UUIDField(db_column='id_zona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre_zona', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_zona', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zona_geografica',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
