# Generated by Django 5.2.17 on 2026-09-15 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_account_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='final_fare',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitado'), ('negotiating', 'Negociando'), ('driver_selected', 'Conductor Seleccionado'), ('en_route', 'En Ruta'), ('arrived', 'Llegó'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('validated', 'Validado'), ('cancelled', 'Cancelado')], default='requested', max_length=20),
        ),
    ]
